server:
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
spring:
  application:
    name: lab-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.47.128:3306/physician?charset=utf8
    username: centos
    password: 123456
mybatis-plus:
  type-aliases-package: com.medical.entity
  mapper-locations: classpath:mapper/medical/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:8088/eureka
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
  server:
    eviction-interval-timer-in-ms: 60000 # 扫描失效服务的间隔时间（缺省为60*1000ms
